#!/bin/bash
THISSCRIPT=$(readlink -f $0)
SCRIPTDIR=$(dirname $THISSCRIPT)
config=${SCRIPTDIR}/.tmpemail
GRABFROM='https://10minutemail.com/10MinuteMail/index.html'

function getemail
{
	email=$(curl -s -L $GRABFROM | grep 'class="mail-address-address"' | sed 's/.*value="\(.*\)" class.*/\1/g')
	echo $email $(date +%s) > ${config}
}
function getage
{
  local curr=$1
  local now=$(date +%s)
  local age=$(( now - curr ))
  local rem
  if [[ $age -lt 600 ]]
  then
    rem=$(( 600 - age ))
  else
    rem=0
  fi
  echo $rem
}

if [ ! -e $config ]
then
  getemail
else
	arr=( $(cat $config) )
  age=$(getage ${arr[1]})
  if [[ $age -lt 2 ]]
  then
    echo renewing...
    sleep 3
    getemail
  fi
fi
arr=( $(cat $config) )
age=$(getage ${arr[1]})
echo "Temporary email: ${arr[0]}"
echo "Time Remaining: $(( age / 60 )) min $(( age % 60 )) sec"
