#!/bin/bash

SCRIPT_ROOT="$HOME/.utils"
PYENVROOT="$SCRIPT_ROOT/pyenvs"

function pyenv_init
{
	PATH_SHORTEN=$(awk -F: '{for(i=2;i<NF;i++){printf("%s:",$i)}printf("%s\n\n",$NF)}' <<<"$PATH")
	if [[ -z $PYENV_ROOT ]]
	then
		export OLDPATH="$PATH"
		export PYENV_ROOT="$PYENVROOT"
		export PATH="$PYENVROOT/bin:$PATH_SHORTEN"
		eval "$(pyenv init -)"
		export PYENV_VERSION=2.7.13
	fi
}
function pyenv_teardown
{
	PATH_SHORTEN=$(awk -F: '{for(i=2;i<NF;i++){printf("%s:",$i)}printf("%s\n\n",$NF)}' <<<"$PATH")
	if [[ ! -z $PYENV_ROOT ]]
	then 
		if [[ ! -z $PYENV_VERSION ]]
		then
			unset PYENV_VERSION
		fi
		export PATH=$OLDPATH
		unset PYENV_ROOT
		unset OLDPATH
	fi
}

