#!/bin/bash
THISSCRIPT=$(readlink -f $0)
SCRIPTNAME=$(basename $THISSCRIPT)
# Change the following line prior to use
LOCAL_COPY=${HOME}/path/to/GarthTex
SYSTEM_COPY=/usr/share/texmf/tex/latex/GarthTex

function usage {
cat <<EOF
The purpose of $SCRIPTNAME is to automate
these steps:
1) sudo cp -uv ${LOCAL_COPY}/GarthTexNotes.sty ${SYSTEM_COPY}
2) sudo cp -uv ${LOCAL_COPY}/GarthTex.sty ${SYSTEM_COPY}
2) sudo texhash
EOF
}
you=`whoami`
if [[ $you != 'root' ]];then
	printf "you must be root!\n"
	usage
	exit 1
fi


cp -uv ${LOCAL_COPY}/GarthTexNotes.sty ${SYSTEM_COPY}
cp -uv ${LOCAL_COPY}/GarthTex.sty ${SYSTEM_COPY}
texhash
