#!/bin/bash

SCRIPTDIR=$(dirname $(readlink -f $0 ))
CONF=$SCRIPTDIR/samba.conf

PNAME="$1"
VARGS=( "$@" )
VARGS=( "${VARGS[@]:1}" )

if [[ "${#VARGS[@]}" -eq 0 ]]
then
	printf "Please specify a file to print.\n"
	exit 1
fi

if [[ "$PNAME" == '-long' ]]
then
	ploc=mthsc_long-basement
elif [[ "$PNAME" == '-martin' ]]
then
	ploc=mthsc_gertrude
else
	printf "No printer specified.  Aborting...\n"
	exit 1
fi

function printto
{
	local incoming fdir flnm
	incoming=$( readlink -f $1 )
	fdir=$(dirname $incoming)
	flnm=$(basename $incoming)
/usr/bin/smbclient -A $CONF //printhost.ces.clemson.edu/$ploc <<SMBCMDS
lcd $fdir
print $flnm
SMBCMDS

}

for fname in ${VARGS[@]}
do
	printto $fname
done
